CREATE TABLE Usuarios(
CPF INTEGER NOT NULL,
Nome VARCHAR(60) NOT NULL,
Usuario VARCHAR(60) NOT NULL,
DataNasc DATE,
DataRegistro DATE NOT NULL,
Email VARCHAR(60),
Senha VARCHAR(15) NOT NULL,
CONSTRAINT PK_Usuarios PRIMARY KEY (CPF)
);

CREATE TABLE Moedas(
COD INTEGER IDENTITY(1,1) NOT NULL,
PacoteMoeda INTEGER NOT NULL,
NomeMoeda VARCHAR(10) NOT NULL CHECK(NomeMoeda in('RP','V-Bucks','Crysta','Diamante','PontosCod')),
ValorPacote DECIMAL (10, 6),
CONSTRAINT PK_Moedas PRIMARY KEY (COD)
);

CREATE TABLE Compras(
CodCompra INTEGER IDENTITY (1234,7),
CodProduto INTEGER NOT NULL,
Qtd INTEGER NOT NULL,
CPF INTEGER NOT NULL,
Metodo VARCHAR(25) CHECK(Metodo in('Pay Pal', 'Pix', 'Boleto bancario', 'Cartao de credito')) NOT NULL,
DataCompra DATE NOT NULL,
CONSTRAINT PK_Compras PRIMARY KEY (CodCompra),
CONSTRAINT FK_CPF FOREIGN KEY (CPF) REFERENCES Usuarios(CPF),
CONSTRAINT FK_CodProduto FOREIGN KEY (CodProduto) REFERENCES Moedas(COD)
);

CREATE TABLE Comprovante(
CodComprovante INTEGER IDENTITY(165,9),
CPF_COMPROVANTE INTEGER, 
IdCompra INTEGER,
Produto INTEGER,
DataComprovante DATE default getdate(),
CONSTRAINT PK_CodComprovante PRIMARY KEY (CodComprovante),
CONSTRAINT FK_CPF_COMPROVANTE FOREIGN KEY (CPF_COMPROVANTE) REFERENCES Usuarios(CPF),
CONSTRAINT FK_IdCompra FOREIGN KEY (IdCompra) REFERENCES Compras(CodCompra),
CONSTRAINT FK_Produto FOREIGN KEY (Produto) REFERENCES Moedas(COD)
)

